---
title: "Acknowledgements"
output: pdf_document
---

Most of these exercises were originally developed as part of a course titled [Risk Analysis in the Earth Sciences](http://bulletins.psu.edu/undergrad/courses/G/GEOSC/450/200910SP) taught in the [Department of Geosciences](http://www.geosc.psu.edu) at the [Pennsylvania State University](http://www.psu.edu) that has been developed by Klaus Keller.  The exercises discussed in this lab manual have been co-developed by a large group (e.g., Ryan Sriver and Patrick Applegate, please see the specific chapters).  The development of this e-textbook was partly supported by the [US National Science Foundation](http://www.nsf.gov) through the [Sustainable Climate Risk Management (SCRiM) network](http://scrimhub.org).  Other support was provided by the [US Department of Energy](http://www.energy.gov), the [Center for Climate Risk Management](http://www.clima.psu.edu/index.php), and the [Rock Ethics Institute](http://rockethics.psu.edu).  

**PJA** thanks the students from the Risk Analysis in the Earth Sciences course, Spring 2013 and Spring 2014, for many helpful comments that improved the exercises.  PJA also thanks AJR for support during the writing of this e-textbook.  

**KK** Thanks all the students in Risk analysis, the members of the Keller research group, and the SCRiM collaborators, for invaluable inputs. Special thanks go to his family, many mentors, and friends for support.