---
title: "Acknowledgements"
date: "7 September 2015"
output: pdf_document
---

The exercises discussed in this lab manual were developed as part of a course titled [Risk Analysis in the Earth Sciences](http://bulletins.psu.edu/undergrad/courses/G/GEOSC/450/200910SP) taught in the [Department of Geosciences](http://www.geosc.psu.edu) at the [Pennsylvania State University](http://www.psu.edu).  This course was designed and originally taught by Klaus Keller.  Many of these exercises were co-developed by a large group, particularly Patrick Applegate, Klaus Keller, and Ryan Sriver; see the list of contributors on the cover page.  

The development of this e-textbook was partly supported by the [US National Science Foundation](http://www.nsf.gov) through the [Sustainable Climate Risk Management (SCRiM) network](http://scrimhub.org).  Other support was provided by the [US Department of Energy](http://www.energy.gov), the [Center for Climate Risk Management](http://www.clima.psu.edu/index.php), and the [Rock Ethics Institute](http://rockethics.psu.edu).  

**PJA** thanks the students from the Risk Analysis in the Earth Sciences course, Spring 2013 and Spring 2014, for many helpful comments that improved the exercises.  PJA also thanks AJR for support during the writing of this e-textbook.  

**KK** thanks the students in the Risk Analysis in the Earth Sciences course, the members of the Keller research group, and his SCRiM collaborators for invaluable inputs.  Special thanks go to his family, many mentors, and friends for support.  