---
output: pdf_document
---

# Contributor Bios

**Patrick J. Applegate** is a Scientific Programmer with the SCRiM (Sustainable Climate Risk Management) network, hosted by the Earth and Environmental Systems Institute at Penn State. In this role, Patrick helps researchers do the computing-related parts of their work more effectively. In particular, Patrick writes new code in support of ongoing projects (especially in the R programming language), curates and documents existing code and data sets, and helps research students learn to write code.  Patrick earned his Ph. D. in Geosciences at Penn State and is first author or co-author of 20 peer-reviewed scientific papers.  His research treats topics including ice sheets and their contributions to sea level rise, methods for estimating the ages of glacial deposits, and the application of statistical methods to problems in the geosciences.  Patrick's e-mail address is patrick.applegate@psu.edu, and his Web site is at http://sites.psu.edu/papplegate/.  

**Ryan L. Sriver** is an Assistant Professor of Atmospheric Sciences at the University of Illinois at Urbana-Champaign (UIUC).  Prior to joining UIUC in the fall of 2012, he worked as a research associate in Penn State’s Department of Geosciences and as a NOAA Climate and Global Change postdoctoral fellow in Penn State’s Department of Meteorology.  He graduated from Purdue University with a PhD in Earth and Atmospheric Sciences.  His research seeks to develop a deeper understanding about the physical processes influencing variability within Earth’s climate system, and to quantify climate change uncertainties relevant to adaptation planning and decision-making.  Ryan's e-mail address is rsriver@illinois.edu, and his Web site is at https://www.atmos.illinois.edu/~rsriver/index.html.  

**Gregory G. Garner** earned a PhD from the Meteorology Department at the Pennsylvania State University while studying ways of improving the skill and value of information provided by air quality forecasts in Baltimore, MD and surrounding cities.  He now focuses his research efforts on robust decision-making, integrated assessment modeling, statistical data analysis, and coupled ethical-epistemic issues in climate change research.  Gregory's e-mail address is ggg121@psu.edu, and his Web site is at https://sites.google.com/site/gggarner121/.  

**Alexander Bakker** is a Postdoctoral scholar in climate and flood risk management at the Pennsylvania State University. He received a Master in Civil Engineering from the Delft University of Technology and obtained a PhD in Regional climate change scenarios at VU University of Amsterdam. His current research focuses on uncertainty quantification and framing in sea level projections and flood risk management. Alexander's email address is bakker@psu.edu.  

**Richard B. Alley** is Evan Pugh University Professor of Geosciences and Associate of the Earth and Environmental Systems Institute at Penn State, as well as co-director of the Penn State Ice and Climate Exploration center. His academic degrees are in geology, with the PhD from the University of Wisconsin, and MSc and BSc from the Ohio State University.  His research addresses the climate history in ice cores, the physics and stability of ice sheets affecting sea-level change, and the influence of glaciers on
the land surface.  He is a member of the US National Academy of Sciences and the Royal Society.  Richard's e-mail address is rba6@psu.edu.  

**Klaus Keller** is a Professor of Geosciences at Penn State, with an adjunct appointment as a Professor of Engineering and Public Policy at Carnegie Mellon University.  At Penn State, Keller directs the Center for Climate Risk Management as well as the research network for Sustainable Climate Risk Management (http://scrimhub.org).  Before joining Penn State, he worked as a research scientist and lecturer at Princeton University and as an engineer in Germany.  Professor Keller graduated from Princeton with a Ph.D. in civil and environmental engineering.  He received master’s degrees from M.I.T. and Princeton as well as an engineer’s degree from the Technische Universität Berlin.  His research addresses two interrelated questions.  First, how can we mechanistically understand past and potentially predict future changes in the climate system? Second, how can we use this information to design sustainable, scientifically sound, technologically feasible, economically efficient, and ethically defensible climate risk management strategies?  He analyzes these questions by mission-oriented basic research covering a wide range of disciplines such as Earth system science, economics, engineering, philosophy, decision science, and statistics.  Klaus' e-mail address is klaus@psu.edu, and his Web site is at http://www3.geosc.psu.edu/~kzk10/.  