---
output:
    pdf_document:
        toc: true
        toc_depth: 3
        fig_caption: true
bibliography: raes.bib
csl: american-geophysical-union.csl
link-citations: true
header-includes:
  \usepackage{setspace}\doublespacing
---

<!-- Copyright 2015 by the Authors -->

<!-- This file is part of Risk Analysis in the Earth Sciences: A Lab Manual with Exercises in R. -->

<!-- This e-textbook is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. -->

<!-- This e-textbook is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. -->

<!-- You should have received a copy of the GNU General Public License along with this e-textbook.  If not, see <http://www.gnu.org/licenses/>. -->

$\pagebreak$

```{r child = "1_summary.Rmd"}
```

$\pagebreak$

```{r child = "2_contrib_bios.Rmd"}
```

$\pagebreak$

```{r child = "3_acknowledgements.Rmd"}
```

$\pagebreak$

```{r child = "4_intro.Rmd"}
```

$\pagebreak$

```{r child = "5_chap0_r_basics.Rmd"}
```

$\pagebreak$

```{r child = "6_chap1_plotting_time_series.Rmd"}
```

$\pagebreak$

```{r child = "7_chap2_normal_distribution.Rmd"}
```

$\pagebreak$

```{r child = "8_chap3_other_distributions.Rmd"}
```

$\pagebreak$

```{r child = "9_chap4_van_dantzig.Rmd"}
```

$\pagebreak$

```{r child = "10_chap5_curve_fitting.Rmd"}
```

$\pagebreak$

```{r child = "11_chap6_coin_bootstrap.Rmd"}
```

$\pagebreak$

```{r child = "12_chap7_sea_level_bootstrap.Rmd"}
```

$\pagebreak$

```{r child = "13_chap8_van_dantzig_uncertain.Rmd"}
```

$\pagebreak$

```{r child = "14_chap9_oat_sensitivity.Rmd"}
```

$\pagebreak$

# References

<div id="refs"></div>


$\pagebreak$

```{r child = "16_license.Rmd"}
```
