---
title: "Risk Analysis in the Earth Sciences: A Lab Manual with Exercises in R"
date: "2 December 2015"
output: pdf_document
---

**Edited by** Patrick J. Applegate and Klaus Keller  

**Contributions by** Patrick J. Applegate, Ryan L. Sriver, Gregory G. Garner, Alexander Bakker, Richard B. Alley, and Klaus Keller  

This book is available from [Leanpub](https://leanpub.com/) at [https://leanpub.com/raes](https://leanpub.com/raes).  

***

Copyright 2015 by the Authors

This e-textbook is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This e-textbook is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this e-textbook.  If not, see <http://www.gnu.org/licenses/>.

***

# Version History

* **Version 1.1, 2 December 2015**: Added Alexander Bakker as an author to Exercise #4.  Updated the front cover, the title page, and the contributor biographies to reflect this change.  Adjusted the introduction and title page to reflect where the book is distributed.
* **Version 1.0, 29 October 2015**: Uploaded an initial version of the book to Leanpub.  This initial version included 10 chapters, including an introduction and nine lab exercises (Exercise #0-Exercise #8).